---
# Handlers for Windows hardening role

- name: restart computer
  ansible.windows.win_reboot:
    reboot_timeout: 600
  listen: "restart windows"

- name: restart windows firewall
  ansible.windows.win_service:
    name: MpsSvc
    state: restarted
  listen: "restart firewall"
