name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    permissions:
      contents: read
      actions: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run bootstrap script in dry-run mode
        run: sudo bash bootstrap.sh --dry-run
      - name: Validate reports directory
        run: |
          if [ ! -d "reports" ] || [ -z "$(ls -A reports)" ]; then
            echo "The reports directory is missing or empty"
            exit 1
          fi
      - name: Upload reports
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: reports/
